name: Bump version

on:
  workflow_dispatch:
    inputs:
      type:
        description: "Release type"
        required: true
        default: "patch"
        options:
          - patch
          - minor
          - major

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno install
      - run: |
          VERSION=$(deno task bump ${{ github.event.inputs.type }})
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add manifest.json
          git commit -m "[skip ci] Bump version"
          git tag -a "$VERSION"
          git push origin "$VERSION"
